name: astro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  graphic: ^2.5.0
  http: ^1.2.2
  http_parser: ^4.0.2
  intl: ^0.19.0
  moving_average: ^0.3.1
  path_provider: ^2.1.4
  responsive_framework: ^1.5.1
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  image_path: "/Users/bharaths/Developer/ASTRO/astro-flutter/assets/Astro Logo copy.jpeg"
  web:
    generate: true
    image_path: "/Users/bharaths/Developer/ASTRO/astro-flutter/assets/Astro Logo copy.jpeg"
    background_color: "#FFFFFF"
    theme_color: "#002770"
