// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGH2jnnUvjA3fg8t-MjggsqXeAjGDkvuU',
    appId: '1:1037689016305:web:e8a2e522b56d8c36327e50',
    messagingSenderId: '1037689016305',
    projectId: 'astro-feb60',
    authDomain: 'astro-feb60.firebaseapp.com',
    storageBucket: 'astro-feb60.appspot.com',
    measurementId: 'G-2EQ3TZQ2Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNpxyioWUess_Y9RWikE7_qK2h8Hdl4k',
    appId: '1:1037689016305:android:ff45d26f55eaf671327e50',
    messagingSenderId: '1037689016305',
    projectId: 'astro-feb60',
    storageBucket: 'astro-feb60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwfrUQTvFuIvrQR8PY3seTTAGp5C2uo4g',
    appId: '1:1037689016305:ios:8844fc196f1ee273327e50',
    messagingSenderId: '1037689016305',
    projectId: 'astro-feb60',
    storageBucket: 'astro-feb60.appspot.com',
    iosBundleId: 'com.example.astro',
  );
}
